apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: axz4bncd9-go 
  janus-idp.io/tekton: axz4bncd9-go
  backstage.io/kubernetes-id: axz4bncd9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: axz4bncd9-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml